### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by joto** [mapbox/pbf.hpp#19]
To check whether everything works on Windows, we need to
* [x] enable appveyor support (@springmeyer)
* [x] add Windows build configuration.

**Comment by springmeyer** [comment]
@joto - good call, I've enabled appveyor. Back to you for creating a build system + configuration. As you know I prefer gyp over cmake because gyp is so easy to install (just download and run the python). Look to variant for an example of a small gyp file + appveyor config: https://github.com/mapbox/variant/blob/master/variant.gyp and https://github.com/mapbox/variant/blob/master/appveyor.yml

**Comment by joto** [comment]
I have added the gyp build config. It works on Linux.
Appveyor says "Project not found or access denied" on https://ci.appveyor.com/project/Mapbox/pbf.hpp.
@springmeyer : Are you sure this is enabled properly?

**Comment by springmeyer** [comment]
@joto - looks like appveyor does not like the `.`, but it is available at https://ci.appveyor.com/project/Mapbox/pbf-hpp

**Comment by BergWerkGIS** [comment]
AppVeyor is all green now (https://github.com/mapbox/pbf.hpp/commits?author=BergWerkGIS):

https://ci.appveyor.com/project/Mapbox/pbf-hpp/build/1.0.4

Automatic build kick off doesn't seem to work, I had to start builds manually on AppVeyor.
Assigning to myself to check back later, if this is just a temporary hick up or needs further investigation.

**Comment by BergWerkGIS** [comment]
Somehow AppVeyor failed to create the webhook.
I added it manually and now it works.
Informed Feodor about it.

**Comment by joto** [comment]
Can someone add an appveyor badge to the README. I can't figure out how to get the right URL.

**Comment by BergWerkGIS** [comment]
Done.
